title: James Gould Codes
markdown: kramdown
url: "https://jamesgould.dev"
baseurl: ""

# for atom feed
author:
  name: James Gould
  email: contact@jamesgould.dev

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "PostGen.exe", "publish.ps1", "azure-pipelines.yml"]
