trigger:

- master

pool:
  vmImage: 'ubuntu-latest'

schedules:
- cron: "5 0 * * *"
  displayName: Daily release for scheduled posts
  branches:
    include: 
     - master
  always: true 

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install jekyll bundler --no-ri --no-rdoc
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- task: CmdLine@2
  inputs:
<<<<<<< HEAD
=======
    script: './PostGen.exe'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Generate posts.json'

- task: CmdLine@2
  inputs:
>>>>>>> abdee8c2996810b704eabe6bbcc3de56d2e32941
    script: bundle exec jekyll build
  displayName: 'Jekyll Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'posts.json'
    targetFolder: '$(Build.SourcesDirectory)/_site'
    OverWrite: true
<<<<<<< HEAD
  displayName: 'Copy post.json to site root'
=======
  displayName: 'Copy posts.json'
>>>>>>> abdee8c2996810b704eabe6bbcc3de56d2e32941

- task: AzureStaticWebApp@0
  inputs:
      app_location: '/_site'
      api_location: 'api'
      output_location: '/_site'
      azure_static_web_apps_api_token: $(deployment_token)
  displayName: 'Deploy to WebApp'
