name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 0 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Jekyll and Bundler
        run: |
          gem install jekyll bundler --no-document
          bundle install --retry=3 --jobs=4

      - name: Build Jekyll site
        run: bundle exec jekyll build --trace

      - name: Copy posts.json to site root
        run: cp posts.json _site/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: '/_site'
          api_location: ''
          output_location: '/_site'
